/**
 * Comprehensive list of language options for booking preferences
 * Sorted alphabetically by label
 */
export const LANGUAGE_OPTIONS: { value: string; label: string }[] = [
  { value: 'afrikaans', label: 'Afrikaans' },
  { value: 'albanian', label: 'Albanian' },
  { value: 'amharic', label: 'Amharic' },
  { value: 'arabic', label: 'Arabic' },
  { value: 'armenian', label: 'Armenian' },
  { value: 'azerbaijani', label: 'Azerbaijani' },
  { value: 'basque', label: 'Basque' },
  { value: 'belarusian', label: 'Belarusian' },
  { value: 'bengali', label: 'Bengali' },
  { value: 'bosnian', label: 'Bosnian' },
  { value: 'bulgarian', label: 'Bulgarian' },
  { value: 'burmese', label: 'Burmese' },
  { value: 'cantonese', label: 'Cantonese' },
  { value: 'catalan', label: 'Catalan' },
  { value: 'cebuano', label: 'Cebuano' },
  { value: 'chinese_mandarin', label: 'Chinese (Mandarin)' },
  { value: 'croatian', label: 'Croatian' },
  { value: 'czech', label: 'Czech' },
  { value: 'danish', label: 'Danish' },
  { value: 'dari', label: 'Dari' },
  { value: 'dutch', label: 'Dutch' },
  { value: 'english', label: 'English' },
  { value: 'estonian', label: 'Estonian' },
  { value: 'farsi_persian', label: 'Farsi (Persian)' },
  { value: 'filipino_tagalog', label: 'Filipino (Tagalog)' },
  { value: 'finnish', label: 'Finnish' },
  { value: 'french', label: 'French' },
  { value: 'french_canadian', label: 'French (Canadian)' },
  { value: 'georgian', label: 'Georgian' },
  { value: 'german', label: 'German' },
  { value: 'greek', label: 'Greek' },
  { value: 'guarani', label: 'Guaraní' },
  { value: 'gujarati', label: 'Gujarati' },
  { value: 'haitian_creole', label: 'Haitian Creole' },
  { value: 'hausa', label: 'Hausa' },
  { value: 'hebrew', label: 'Hebrew' },
  { value: 'hindi', label: 'Hindi' },
  { value: 'hungarian', label: 'Hungarian' },
  { value: 'icelandic', label: 'Icelandic' },
  { value: 'igbo', label: 'Igbo' },
  { value: 'indonesian', label: 'Indonesian' },
  { value: 'irish', label: 'Irish' },
  { value: 'italian', label: 'Italian' },
  { value: 'japanese', label: 'Japanese' },
  { value: 'javanese', label: 'Javanese' },
  { value: 'kannada', label: 'Kannada' },
  { value: 'kazakh', label: 'Kazakh' },
  { value: 'khmer', label: 'Khmer' },
  { value: 'kinyarwanda', label: 'Kinyarwanda' },
  { value: 'korean', label: 'Korean' },
  { value: 'kurdish', label: 'Kurdish' },
  { value: 'lao', label: 'Lao' },
  { value: 'latvian', label: 'Latvian' },
  { value: 'lithuanian', label: 'Lithuanian' },
  { value: 'macedonian', label: 'Macedonian' },
  { value: 'malay', label: 'Malay' },
  { value: 'malayalam', label: 'Malayalam' },
  { value: 'maltese', label: 'Maltese' },
  { value: 'maori', label: 'Māori' },
  { value: 'marathi', label: 'Marathi' },
  { value: 'mongolian', label: 'Mongolian' },
  { value: 'nepali', label: 'Nepali' },
  { value: 'norwegian', label: 'Norwegian' },
  { value: 'oriya', label: 'Oriya' },
  { value: 'pashto', label: 'Pashto' },
  { value: 'polish', label: 'Polish' },
  { value: 'portuguese', label: 'Portuguese' },
  { value: 'portuguese_brazilian', label: 'Portuguese (Brazilian)' },
  { value: 'punjabi', label: 'Punjabi' },
  { value: 'quechua', label: 'Quechua' },
  { value: 'romanian', label: 'Romanian' },
  { value: 'russian', label: 'Russian' },
  { value: 'samoan', label: 'Samoan' },
  { value: 'serbian', label: 'Serbian' },
  { value: 'sesotho', label: 'Sesotho' },
  { value: 'shona', label: 'Shona' },
  { value: 'sindhi', label: 'Sindhi' },
  { value: 'sinhala', label: 'Sinhala' },
  { value: 'slovak', label: 'Slovak' },
  { value: 'slovenian', label: 'Slovenian' },
  { value: 'somali', label: 'Somali' },
  { value: 'spanish', label: 'Spanish' },
  { value: 'sundanese', label: 'Sundanese' },
  { value: 'swahili', label: 'Swahili' },
  { value: 'swedish', label: 'Swedish' },
  { value: 'tamil', label: 'Tamil' },
  { value: 'telugu', label: 'Telugu' },
  { value: 'thai', label: 'Thai' },
  { value: 'tibetan', label: 'Tibetan' },
  { value: 'tigrinya', label: 'Tigrinya' },
  { value: 'tongan', label: 'Tongan' },
  { value: 'turkish', label: 'Turkish' },
  { value: 'turkmen', label: 'Turkmen' },
  { value: 'ukrainian', label: 'Ukrainian' },
  { value: 'urdu', label: 'Urdu' },
  { value: 'uzbek', label: 'Uzbek' },
  { value: 'vietnamese', label: 'Vietnamese' },
  { value: 'welsh', label: 'Welsh' },
  { value: 'xhosa', label: 'Xhosa' },
  { value: 'yiddish', label: 'Yiddish' },
  { value: 'yoruba', label: 'Yoruba' },
  { value: 'zulu', label: 'Zulu' },
  { value: 'other', label: 'Other language (not listed)' },
]
