/**
 * DUMMY STUDENT DATABASE FOR LOCAL DEMO
 * This file contains in-memory student data for testing the tourist flow
 * without requiring a real database connection.
 *
 * To replace with real database later:
 * 1. Remove this file
 * 2. Update API routes in /src/app/api/demo/ to use Prisma
 * 3. Update the demo page to use the production endpoints
 */

export interface DummyStudent {
  id: string
  name: string
  email: string
  city: 'Paris' | 'London'
  homeCountry: string
  languages: string[]
  hourlyRate: number
  maxGuests: number
  bio: string
  focusAreas: string[]
  institute: string
  gender: 'male' | 'female'
  tripsHosted: number
  averageRating: number | null
  noShowCount: number
  reliabilityBadge: 'gold' | 'silver' | 'bronze' | null
  interests: string[]
  availableDates: string[] // For simplicity, just dates as strings
}

export const DUMMY_STUDENTS: DummyStudent[] = [
  // PARIS STUDENTS
  {
    id: 'paris-1',
    name: 'Marie Laurent',
    email: 'marie.laurent@sorbonne.fr',
    city: 'Paris',
    homeCountry: 'France',
    languages: ['French', 'English', 'Spanish'],
    hourlyRate: 25,
    maxGuests: 6,
    bio: 'Passionate about Parisian art and culture. I love showing visitors the hidden gems of the Louvre and Musée d\'Orsay. As an art history student, I can bring masterpieces to life with fascinating stories.',
    focusAreas: ['museums', 'art', 'history', 'culture'],
    institute: 'Sorbonne University',
    gender: 'female',
    tripsHosted: 23,
    averageRating: 4.8,
    noShowCount: 0,
    reliabilityBadge: 'gold',
    interests: ['art', 'history', 'museums', 'culture', 'architecture'],
    availableDates: ['2025-12-01', '2025-12-02', '2025-12-05'],
  },
  {
    id: 'paris-2',
    name: 'Jean-Pierre Dubois',
    email: 'jp.dubois@sciences-po.fr',
    city: 'Paris',
    homeCountry: 'France',
    languages: ['French', 'English'],
    hourlyRate: 22,
    maxGuests: 4,
    bio: 'Food enthusiast and local Parisian. I specialize in culinary tours through authentic Parisian cafés, bakeries, and hidden bistros. Let me show you where locals really eat!',
    focusAreas: ['food', 'cafes', 'restaurants', 'local', 'budget-friendly'],
    institute: 'Sciences Po Paris',
    gender: 'male',
    tripsHosted: 15,
    averageRating: 4.6,
    noShowCount: 0,
    reliabilityBadge: 'silver',
    interests: ['food', 'restaurants', 'local culture', 'budget travel'],
    availableDates: ['2025-12-01', '2025-12-03', '2025-12-04'],
  },
  {
    id: 'paris-3',
    name: 'Sophie Chen',
    email: 'sophie.chen@hec.fr',
    city: 'Paris',
    homeCountry: 'China',
    languages: ['Mandarin', 'English', 'French'],
    hourlyRate: 28,
    maxGuests: 8,
    bio: 'International student who knows what it\'s like to be a first-time visitor! I specialize in helping Asian tourists navigate Paris, with language support in Mandarin. Family-friendly and kid-approved.',
    focusAreas: ['first-time', 'kids', 'family', 'shopping', 'photography'],
    institute: 'HEC Paris',
    gender: 'female',
    tripsHosted: 31,
    averageRating: 4.9,
    noShowCount: 0,
    reliabilityBadge: 'gold',
    interests: ['shopping', 'photography', 'family activities', 'kid-friendly'],
    availableDates: ['2025-12-02', '2025-12-04', '2025-12-06'],
  },
  {
    id: 'paris-4',
    name: 'Ahmed El-Sayed',
    email: 'ahmed.elsayed@upec.fr',
    city: 'Paris',
    homeCountry: 'Egypt',
    languages: ['Arabic', 'French', 'English'],
    hourlyRate: 20,
    maxGuests: 5,
    bio: 'Architecture student passionate about Gothic and modern Parisian buildings. I offer unique walking tours exploring architectural marvels from Notre-Dame to La Défense.',
    focusAreas: ['architecture', 'history', 'photography', 'walking tours'],
    institute: 'Université Paris-Est Créteil',
    gender: 'male',
    tripsHosted: 8,
    averageRating: 4.5,
    noShowCount: 1,
    reliabilityBadge: 'bronze',
    interests: ['architecture', 'history', 'photography', 'culture'],
    availableDates: ['2025-12-01', '2025-12-05', '2025-12-07'],
  },
  {
    id: 'paris-5',
    name: 'Isabella Martinez',
    email: 'isabella.m@dauphine.fr',
    city: 'Paris',
    homeCountry: 'Spain',
    languages: ['Spanish', 'English', 'French', 'Italian'],
    hourlyRate: 30,
    maxGuests: 10,
    bio: 'Nightlife expert and party enthusiast! I can show you the best bars, clubs, and live music venues in Paris. Perfect for groups of friends looking for an authentic Parisian night out.',
    focusAreas: ['nightlife', 'music', 'bars', 'clubs', 'young crowd'],
    institute: 'Paris Dauphine University',
    gender: 'female',
    tripsHosted: 19,
    averageRating: 4.7,
    noShowCount: 0,
    reliabilityBadge: 'silver',
    interests: ['nightlife', 'music', 'bars', 'live music', 'dancing'],
    availableDates: ['2025-12-03', '2025-12-06', '2025-12-08'],
  },
  {
    id: 'paris-6',
    name: 'Lucas Moreau',
    email: 'lucas.moreau@polytechnique.fr',
    city: 'Paris',
    homeCountry: 'France',
    languages: ['French', 'English', 'German'],
    hourlyRate: 24,
    maxGuests: 4,
    bio: 'Tech-savvy engineering student who loves exploring innovative Paris. I can show you Station F (world\'s largest startup campus), tech museums, and futuristic architecture.',
    focusAreas: ['innovation', 'technology', 'modern', 'startup culture'],
    institute: 'École Polytechnique',
    gender: 'male',
    tripsHosted: 5,
    averageRating: null,
    noShowCount: 0,
    reliabilityBadge: null,
    interests: ['technology', 'innovation', 'modern architecture', 'startups'],
    availableDates: ['2025-12-02', '2025-12-04', '2025-12-06'],
  },
  {
    id: 'paris-7',
    name: 'Yuki Tanaka',
    email: 'yuki.tanaka@inalco.fr',
    city: 'Paris',
    homeCountry: 'Japan',
    languages: ['Japanese', 'English', 'French'],
    hourlyRate: 26,
    maxGuests: 6,
    bio: 'Love manga, anime, and Japanese pop culture? I know all the best Japanese bookstores, anime shops, and cosplay spots in Paris. Also great for quiet, contemplative garden tours.',
    focusAreas: ['culture', 'shopping', 'gardens', 'photography', 'peaceful'],
    institute: 'INALCO (Languages O\')',
    gender: 'female',
    tripsHosted: 12,
    averageRating: 4.9,
    noShowCount: 0,
    reliabilityBadge: 'silver',
    interests: ['culture', 'shopping', 'gardens', 'photography', 'nature'],
    availableDates: ['2025-12-01', '2025-12-03', '2025-12-05'],
  },
  {
    id: 'paris-8',
    name: 'Thomas Bernard',
    email: 'thomas.bernard@assas.fr',
    city: 'Paris',
    homeCountry: 'France',
    languages: ['French', 'English'],
    hourlyRate: 23,
    maxGuests: 3,
    bio: 'Law student and history buff. I specialize in Revolutionary Paris tours, covering major historical sites with deep dives into French history and politics.',
    focusAreas: ['history', 'politics', 'revolution', 'walking tours'],
    institute: 'Panthéon-Assas University',
    gender: 'male',
    tripsHosted: 7,
    averageRating: 4.4,
    noShowCount: 0,
    reliabilityBadge: 'bronze',
    interests: ['history', 'politics', 'museums', 'culture'],
    availableDates: ['2025-12-02', '2025-12-05', '2025-12-07'],
  },

  // LONDON STUDENTS
  {
    id: 'london-1',
    name: 'Emma Watson',
    email: 'emma.watson@ucl.ac.uk',
    city: 'London',
    homeCountry: 'United Kingdom',
    languages: ['English', 'French'],
    hourlyRate: 22,
    maxGuests: 5,
    bio: 'Theatre enthusiast and drama student. I offer tours of London\'s West End, including backstage insights and the best spots to catch affordable shows.',
    focusAreas: ['theatre', 'arts', 'entertainment', 'culture'],
    institute: 'University College London',
    gender: 'female',
    tripsHosted: 18,
    averageRating: 4.7,
    noShowCount: 0,
    reliabilityBadge: 'gold',
    interests: ['theatre', 'arts', 'culture', 'entertainment', 'music'],
    availableDates: ['2025-12-01', '2025-12-03', '2025-12-06'],
  },
  {
    id: 'london-2',
    name: 'Raj Patel',
    email: 'raj.patel@imperial.ac.uk',
    city: 'London',
    homeCountry: 'India',
    languages: ['Hindi', 'English', 'Gujarati'],
    hourlyRate: 20,
    maxGuests: 4,
    bio: 'Engineering student passionate about London\'s industrial heritage. I love showing visitors the Science Museum, Greenwich, and explaining the engineering marvels of the city.',
    focusAreas: ['science', 'engineering', 'museums', 'history'],
    institute: 'Imperial College London',
    gender: 'male',
    tripsHosted: 14,
    averageRating: 4.6,
    noShowCount: 1,
    reliabilityBadge: 'silver',
    interests: ['science', 'engineering', 'museums', 'technology', 'history'],
    availableDates: ['2025-12-02', '2025-12-04', '2025-12-07'],
  },
  {
    id: 'london-3',
    name: 'Olivia Brown',
    email: 'olivia.brown@lse.ac.uk',
    city: 'London',
    homeCountry: 'United Kingdom',
    languages: ['English', 'Spanish'],
    hourlyRate: 28,
    maxGuests: 8,
    bio: 'Foodie and market explorer! I specialize in food tours through Borough Market, Camden Market, and Brick Lane. Perfect for families and food lovers.',
    focusAreas: ['food', 'markets', 'family', 'kid-friendly', 'local'],
    institute: 'London School of Economics',
    gender: 'female',
    tripsHosted: 26,
    averageRating: 4.8,
    noShowCount: 0,
    reliabilityBadge: 'gold',
    interests: ['food', 'markets', 'family activities', 'kid-friendly', 'local culture'],
    availableDates: ['2025-12-01', '2025-12-04', '2025-12-06'],
  },
  {
    id: 'london-4',
    name: 'Liam O\'Connor',
    email: 'liam.oconnor@kcl.ac.uk',
    city: 'London',
    homeCountry: 'Ireland',
    languages: ['English', 'Irish'],
    hourlyRate: 24,
    maxGuests: 6,
    bio: 'Pub culture expert! As an Irish student in London, I know the best traditional pubs, craft beer spots, and historic taverns. Great for evening tours.',
    focusAreas: ['pubs', 'nightlife', 'history', 'local', 'socializing'],
    institute: 'King\'s College London',
    gender: 'male',
    tripsHosted: 11,
    averageRating: 4.5,
    noShowCount: 0,
    reliabilityBadge: 'bronze',
    interests: ['pubs', 'nightlife', 'history', 'socializing', 'culture'],
    availableDates: ['2025-12-03', '2025-12-05', '2025-12-08'],
  },
  {
    id: 'london-5',
    name: 'Fatima Al-Rashid',
    email: 'fatima.rashid@soas.ac.uk',
    city: 'London',
    homeCountry: 'Saudi Arabia',
    languages: ['Arabic', 'English', 'French'],
    hourlyRate: 26,
    maxGuests: 5,
    bio: 'Cultural anthropology student specializing in multicultural London. I offer tours exploring London\'s diverse neighborhoods, from Chinatown to Little India.',
    focusAreas: ['culture', 'diversity', 'food', 'neighborhoods', 'shopping'],
    institute: 'SOAS University of London',
    gender: 'female',
    tripsHosted: 9,
    averageRating: 4.8,
    noShowCount: 0,
    reliabilityBadge: 'silver',
    interests: ['culture', 'diversity', 'food', 'shopping', 'local culture'],
    availableDates: ['2025-12-02', '2025-12-04', '2025-12-06'],
  },
  {
    id: 'london-6',
    name: 'Marcus Johnson',
    email: 'marcus.j@qmul.ac.uk',
    city: 'London',
    homeCountry: 'United Kingdom',
    languages: ['English'],
    hourlyRate: 21,
    maxGuests: 4,
    bio: 'Street art and graffiti expert! I run tours through Shoreditch, Brick Lane, and Camden exploring incredible street art, including works by Banksy.',
    focusAreas: ['art', 'street art', 'photography', 'modern', 'youth culture'],
    institute: 'Queen Mary University',
    gender: 'male',
    tripsHosted: 6,
    averageRating: 4.7,
    noShowCount: 0,
    reliabilityBadge: 'bronze',
    interests: ['art', 'street art', 'photography', 'modern culture', 'urban exploration'],
    availableDates: ['2025-12-01', '2025-12-05', '2025-12-07'],
  },
  {
    id: 'london-7',
    name: 'Hannah Cohen',
    email: 'hannah.cohen@arts.ac.uk',
    city: 'London',
    homeCountry: 'United Kingdom',
    languages: ['English', 'Hebrew'],
    hourlyRate: 25,
    maxGuests: 7,
    bio: 'Fashion student and shopping guide! I know all the best vintage shops, designer outlets, and hidden boutiques in London. Perfect for fashion lovers and shoppers.',
    focusAreas: ['fashion', 'shopping', 'vintage', 'photography', 'style'],
    institute: 'University of the Arts London',
    gender: 'female',
    tripsHosted: 13,
    averageRating: 4.6,
    noShowCount: 0,
    reliabilityBadge: 'silver',
    interests: ['fashion', 'shopping', 'photography', 'art', 'design'],
    availableDates: ['2025-12-02', '2025-12-03', '2025-12-06'],
  },
  {
    id: 'london-8',
    name: 'Carlos Mendoza',
    email: 'carlos.m@westminster.ac.uk',
    city: 'London',
    homeCountry: 'Mexico',
    languages: ['Spanish', 'English', 'Portuguese'],
    hourlyRate: 23,
    maxGuests: 6,
    bio: 'Photography student who loves capturing London\'s beauty. I offer photo-walk tours to the best Instagram spots, hidden viewpoints, and golden hour locations.',
    focusAreas: ['photography', 'Instagram', 'viewpoints', 'architecture', 'creative'],
    institute: 'University of Westminster',
    gender: 'male',
    tripsHosted: 10,
    averageRating: 4.9,
    noShowCount: 0,
    reliabilityBadge: 'silver',
    interests: ['photography', 'architecture', 'art', 'creativity', 'social media'],
    availableDates: ['2025-12-01', '2025-12-04', '2025-12-08'],
  },
]

/**
 * Get students by city
 */
export function getStudentsByCity(city: string): DummyStudent[] {
  return DUMMY_STUDENTS.filter(
    (student) => student.city.toLowerCase() === city.toLowerCase()
  )
}

/**
 * Get student by ID
 */
export function getStudentById(id: string): DummyStudent | undefined {
  return DUMMY_STUDENTS.find((student) => student.id === id)
}
